### ISSUE TITLE
Does it support sockets?

### ISSUE THREAD

**Issue by reinerBa** [Barryrowe/custom-ntlm-default-proxy#1]
Hi, does your library forward socket especially websockets as well?
thanks in advance

**Comment by Barryrowe** [comment]
@reinerBa I have not tested this, and it's been a while since I've looked at this library in all honesty. I am not familiar with the underlying workings of opening and maintaining web sockets in .NET, so I can't say for sure if these settings would be picked up. I don't know that they would use the same mechanisms, as websockets are much more involved, and if you're using SignalR, they may have abstracted away something entirely different.

That being said, it looks like there is a ```Proxy``` property that is of type ```IWebProxy```  {[MSDN ClientWebSocketOptions](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions.proxy(v=vs.110).aspx)} so this library may do what you need it to do, but I can't confirm.
